name: Update badges

on:
  workflow_dispatch:
  schedule:
    # Runs at 01:00AM UTC+7 = 00:00AM +7
    - cron: "5 * * * *"
    
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.ADNAN_TOKEN }}
          REPOSITORY: adnanadrika/adnanadrika # optional, By default, it will automatically use the repository who's executing the workflow.
          COMMIT_MESSAGE: "My commit message to update badges" # optional
          CREDLY_USER: muhammad-adnan-nur-adrika # optional, but default will use the same from github
          CREDLY_SORT: POPULAR # optional, this is the two forms from credly sort, more popular or recent first, by default use RECENT
